work_dir: ./runs/ntu_cv_agcn_joint
model_saved_name: ./runs/ntu_cv_agcn_joint
# feeder
feeder: feeders.feeder.Feeder_2D
train_feeder_args:
  data_path: ./data/ntu/xsub/train_label.pkl
  label_path: ./data/ntu/xsub/train_label.pkl
  debug: False
  split: xview_train
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ntu/xsub/val_data_joint.npy
  label_path: ./data/ntu/xsub/val_label.pkl
  debug: False
  split: xview_val

# model
model: model.agcn.Model
model_args:
  num_class: 60
  num_point: 17
  num_person: 2
  in_channels: 2
  drop_out: 0.5
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'
    num_node: 17

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [40, 50]
warm_up_epoch: 5

# training
device: [0] #, 1 ,2
batch_size: 32
test_batch_size: 32
num_epoch: 60
nesterov: True

phase: train
num_worker: 8